### ISSUE TITLE
[SM] Exception reported: Property "m_hOwnerEntity" not found (entity 113/cs_ragdoll

### ISSUE THREAD

**Issue by brushu** [Maxximou5/csgo-deathmatch#90] opened 2018-09-12 18:40 UTC
L 09/11/2018 - 09:23:22: [SM] Exception reported: Property "m_hOwnerEntity" not found (entity 113/cs_ragdoll)
L 09/11/2018 - 09:23:22: [SM] Blaming: deathmatch.smx
L 09/11/2018 - 09:23:22: [SM] Call stack trace:
L 09/11/2018 - 09:23:22: [SM]   [0] GetEntPropEnt
L 09/11/2018 - 09:23:22: [SM]   [1] Line 3106, deathmatch.sp::Event_Sound
L 09/11/2018 - 09:25:36: Error log file session closed.

**Comment by Maxximou5** [comment] 2018-09-12 22:14
In the future please provide your version of SourceMod and version of Deathmatch.

Duplicate of #88 

This error won't exist in future versions.

**Closed** 2024-01-21 19:29 UTC
Labels: bug, duplicate
